# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-15 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20170214_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='\u6559\u5e08\u63cf\u8ff0'),
        ),
    ]
